version: "3.8"

services:
  marketiin-api:
    build: .
    container_name: marketiin-api
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped