version: "3.8"

services:
  marketiin-api:
    build: .
    container_name: marketiin-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    command: http marketiin-api:3000
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=32Rpk8LQAWU5AHmMTO2oWAwVEoI_5ZNd7rapgZsYY9hEDxpYu
    depends_on:
      - marketiin-api